# Site
#repository: sproogen/resume-theme
#favicon: images/favicon.ico

github: [metadata]

# Personal info
name: Claire Jellison
title: Research Associate
email: clairesjellison@gmail.com
#website: www.github.com/zumiko

darkmode: false

# Social links
#twitter_username: evensocj
github_username:  zumiko
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: claire-jellison
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs

  I grew up in [Bishop, CA](https://bishopvisitor.com/). From there, I moved to Portland, OR to attend Reed College. At Reed, I double majored in math and econ 
  and wrote my senior [thesis](https://github.com/zumiko/thesis) on peer effects within online crowdfunding. After graduating, 
  I interned remotely for the Federal Reserve Bank of Philadelphia and then briefly at Texas A&M. Then I returned to the Philly Fed
  to join the Research Department where I've worked on machine learning and empirical macro research, policy briefings, and improving my 
  ping pong skills.  


#Test out a [mini crossword](minicrossword.html). 
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Skills Section
more_title: Skills
more_content: | # this will include new lines to allow paragraphs
  - Python, R, SQL, Stata
  - Proficient in Spanish 
  - Microsoft Office 
  - Google Suite 



# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
