theme: jekyll-theme-cayman

title: CSJ
description:   resume_linkedin_url:          "https://www.linkedin.com/in/claire-jellison"
print_social_links:      true
# social-links
social_links:
  #resume_github_url:            
  #resume_twitter_url:           


